baseURL = 'https://slchangtw.github.io'
languageCode = 'en-us'
title = 'Be a Problem Solver'

theme = 'github.com/nodejh/hugo-theme-mini'

[social]
  github = "https://github.com/slchangtw"
  linkedin = "https://www.linkedin.com/in/slchang"

[params]
    name = "Shun-Lung Chang" 
    enableComments = "true"